# https://docs.travis-ci.com/user/job-lifecycle

language: node_js

node_js:
- '12.0'

git:
  depth: 5

cache:
  yarn: true

install:
- yarn install --frozen-lockfile

stages:
  - test

jobs:
  include:
    - stage: test
      script:
        - yarn run check
